



# learnKOREAN - Emotional Classification


- github : https://github.com/Maxpridy




# http://movie.naver.com/movie/bi/mi/basic.nhn?code=45290
    
네이버 영화 인터스텔라 리뷰들을 이용해서 분석.

지도 학습으로 그냥 아무런 형태소 분석 없이 Binary Classification을 간단하게 해본다.

인터스텔라는 평점이 9가 넘어가서 불균형이 심하지만 데이터가 매우 많다.(그리고 내가 좋아한다.)


8점 이상은 긍정, 7점 이하는 부정으로 했음에도 불구하고 긍정 : 42289, 부정 : 5293이다.

평균평점이 9점이니까 그럴만도하다..

사실 정확도도 그냥 긍정으로 다 찍어버려도 90% 나오는건데... 쩝.




In [174]:
fr = open('reviews.txt','r')
reviews = list(map(lambda x:x[:-1], fr.readlines()))
fr.close()

fl = open('labels.txt','r')
labels = list(map(lambda x:x[:-1].upper(), fl.readlines()))
fl.close()

In [175]:
len(reviews)

47582

In [176]:
reviews[0]

'인셉션은 대단하다 느꼈는데, 인터스텔라는 경이롭다고 느껴진다.'

In [177]:
labels[0]

'POSITIVE'

In [48]:
def print_review_and_label(i):
    print(labels[i] + "\t:\t" + reviews[i][:-1] + "...")


In [49]:
print("labels.txt \t : \t reviews.txt\n")

count = 1
for i in range(len(reviews)):
    if(labels[i] == 'NEGATIVE'):
        count = count+1
        print(count)
        print_review_and_label(i)
        
# ... 음..........................

labels.txt 	 : 	 reviews.txt

2
NEGATIVE	:	이 평점은 1점이 아니라 11점 버튼이 없어서 누르지 못한 나의 안타까운 마음을 표현한 것이...
3
NEGATIVE	:	와 진짜 이걸 빠는구나... 재미없는건 재미없는건데....
4
NEGATIVE	:	거품이 너무 많이 낀듯;; 과학적으로 오류도 많고 앞뒤 안 맞는 내용도 있다. 재미없다고 하면 이해못해서 그렇다고 욕먹음ㅋㅋㅋ 솔직히7점 정도 작품인데 거품많이끼고 아는''체''때문에 평가가 높아지는 작품인...
5
NEGATIVE	:	너무 과대포장 되었다...
6
NEGATIVE	:	실제 미국 캐나다에서는 영화상영나가는사람들엄청많고평도엄청안좋고 말도안되는영화라고 말많은데  한국은ㅋㅋㅋ...
7
NEGATIVE	:	도대체 영화보고난후에 사람들 반응이싸늘했는데 평점진짜 혐오스럽네스토리는 영화진행될수록 산으로가는데 지구가 위험하다면서 여정을떠나더니 그 주제는 안중에도없다 딸과아버지의 사랑이 큰 주제였더냐왜 유독 우리나라에서만 찬양하는거냐 ......
8
NEGATIVE	:	이영화가왜 우리나라에서만 잘되고 다른나라에서만 망한건지 이해가된다 나만그런건가? 노잼이...
9
NEGATIVE	:	지성인인척 영화볼줄 아는척 안습이네요 솔직히 복선깔아논거랑 돈 왕창 쏟아부은 cg빼면 내용은 노잼입니다 잘 졸다 왔습니다. 스토리상 에서 복선만 인정 나머지는 노잼  인셉션>>>인터스텔...
10
NEGATIVE	:	희대의 거품영화. 영화가 쓰레기라 1점 주는게 아니라 이 영화로 허세부리는사람에게 1점 주는거다...
11
NEGATIVE	:	허세충들이 찬양하기에는 딱 좋은 영화..  우주관련 다큐가 휠씬 낫...
12
NEGATIVE	:	나에게 보지말라고 보내준 모스부호를 무시한결과는 엄청나...
13
NEGATIVE	:	네티즌 평점에서부터 한국인 특유의 허세를 보여주는 작품... 막상 상대성이론도 모르는 놈들이 유식해 보일려고 이해했다, 재미있다고 난리치는거 보면 답이 없다.재미없었음 흥행의 이유를 모르

In [52]:
import numpy as np
from collections import Counter

In [53]:
positive_counts = Counter()
negative_counts = Counter()
total_counts = Counter()

In [54]:
for i in range(len(reviews)):
    if(labels[i] == 'POSITIVE'):
        for word in reviews[i].split(" "):
            positive_counts[word] += 1
            total_counts[word] += 1
    else:
        for word in reviews[i].split(" "):
            negative_counts[word] += 1
            total_counts[word] += 1

In [55]:
positive_counts.most_common()

[('', 6108),
 ('영화', 4142),
 ('정말', 3372),
 ('진짜', 2589),
 ('영화를', 2273),
 ('최고의', 2203),
 ('이', 2135),
 ('수', 1888),
 ('너무', 1496),
 ('그냥', 1384),
 ('더', 1331),
 ('영화가', 1324),
 ('영화는', 1239),
 ('꼭', 1181),
 ('보고', 1166),
 ('이런', 1121),
 ('영화.', 1117),
 ('내', 1096),
 ('본', 1091),
 ('말이', 1078),
 ('그', 1071),
 ('놀란', 1019),
 ('내가', 939),
 ('잘', 842),
 ('있는', 804),
 ('또', 794),
 ('이건', 745),
 ('다시', 744),
 ('좀', 700),
 ('다', 626),
 ('볼', 602),
 ('것', 590),
 ('역시', 583),
 ('보는', 580),
 ('3시간이', 573),
 ('대한', 572),
 ('크리스토퍼', 566),
 ('없는', 563),
 ('어떻게', 551),
 ('그리고', 548),
 ('인생', 537),
 ('한', 522),
 ('이렇게', 515),
 ('영화관에서', 492),
 ('놀란의', 489),
 ('한번', 488),
 ('내내', 471),
 ('가장', 461),
 ('할', 459),
 ('하는', 434),
 ('인터스텔라', 432),
 ('와', 425),
 ('최고', 422),
 ('시간이', 420),
 ('평점', 409),
 ('하지만', 402),
 ('아이맥스로', 398),
 ('.', 398),
 ('많이', 393),
 ('우주에', 390),
 ('대단한', 389),
 ('인간의', 387),
 ('우주의', 386),
 ('조금', 379),
 ('영화다.', 371),
 ('재밌게', 368),
 ('감독의', 366),
 ('보면', 365),
 ('놀란은', 361

In [63]:
pos_neg_ratios = Counter()

for term,cnt in list(total_counts.most_common()):
    if(cnt > 100):
        pos_neg_ratio = positive_counts[term] / float(negative_counts[term]+1)
        pos_neg_ratios[term] = pos_neg_ratio

for word,ratio in pos_neg_ratios.most_common():
    if(ratio > 1):
        pos_neg_ratios[word] = np.log(ratio)
    else:
        pos_neg_ratios[word] = -np.log((1 / (ratio+0.01)))

In [64]:
pos_neg_ratios.most_common()

[('말로', 5.7838251823297373),
 ('내인생', 5.2781146592305168),
 ('필요없다', 4.8751973232011512),
 ('꼭보세요', 4.8202815656050371),
 ('필요없다.', 4.7706846244656651),
 ('인생영화', 4.7621739347977563),
 ('필요없는', 4.5108595065168497),
 ('눈물이', 4.4886363697321396),
 ('표현할', 4.4773368144782069),
 ('최고의', 4.3653708366271395),
 ('인생', 4.3400879454535515),
 ('꼭', 4.240903472141146),
 ('감히', 4.2121275978784842),
 ('평생', 4.1190371748124726),
 ('최고', 4.0990951649806986),
 ('여운이', 4.0661736852554045),
 ('죽기전에', 4.0517849478033048),
 ('3시간이', 4.048300623720694),
 ('말이', 4.0384237723025018),
 ('안보면', 3.9796816539019608),
 ('모르게', 3.970291913552122),
 ('소름이', 3.9269116179218968),
 ('필요', 3.9252682321781664),
 ('몰입해서', 3.9219733362813143),
 ('생에', 3.912023005428146),
 ('느낄', 3.9053340172773492),
 ('시간가는줄', 3.9019726695746448),
 ('살면서', 3.8836235309064482),
 ('영화!!', 3.8286413964890951),
 ('생애', 3.7689221617874726),
 ('경이롭다.', 3.755369195382769),
 ('보세요', 3.7226768336972271),
 ('보고싶은', 3.6971782569286313),
 ('경이로움', 3.

In [66]:
list(reversed(pos_neg_ratios.most_common()))[0:30]
# 음....................

[('지루하고', -1.0763800632689959),
 ('평점이', -0.56010151739366976),
 ('기대가', -0.32830279898303005),
 ('없고', -0.16403810943294475),
 ('다들', 0.039220713153281329),
 ('솔직히', 0.087011376989629685),
 ('훨씬', 0.22314355131420976),
 ('기대하고', 0.24116205681688804),
 ('생각보다', 0.30873548164961323),
 ('재미는', 0.33349160848307507),
 ('재미가', 0.34294475112683043),
 ('보다가', 0.40546510810816438),
 ('그렇게', 0.42433359241254714),
 ('뭐', 0.46798546508949834),
 ('딱', 0.47762755435639487),
 ('그런지', 0.53492317534505118),
 ('나름', 0.61090908232297314),
 ('기대를', 0.61455690596672374),
 ('스토리가', 0.63779708547678038),
 ('내용은', 0.65587578576271366),
 ('지루한', 0.66904962898088483),
 ('이게', 0.68072466056138814),
 ('저는', 0.70556970055850243),
 ('결국', 0.81377516834856001),
 ('내용도', 0.82098055206983034),
 ('너무', 0.82286614004981196),
 ('아니다', 0.8286926725561693),
 ('넘', 0.85938259960227559),
 ('사람들이', 0.86808863005627734),
 ('좀', 0.88465364693097248)]

In [71]:
vocab = set(total_counts.keys())
vocab_size = len(vocab)
print(vocab_size)

119893


In [72]:
list(vocab)

['',
 '퀄리티로',
 '재미있었다.지구환경에',
 '영화임',
 '중요하지만...',
 '답답하기도',
 '든다는건',
 '그걸전하는거같네요',
 '벽이',
 '내용면에서는',
 '참신함만으로',
 '개소름...',
 '어린왕자와',
 '구원과',
 '이해는안되는데..나도모르게',
 '있습니다.OCN에서',
 '게임도',
 '이해할듯...',
 '최고아닌게',
 '그은',
 '상업영화',
 '하거나',
 '힘주는',
 '나을것도',
 '주인공.2.',
 '욕심에',
 '번은',
 '이해못하면',
 '살았겠죠',
 '선사햇다',
 '2%아쉬움이',
 '흥미진진했다.',
 '영화음악',
 '알거같네요',
 '감동적입니다.',
 'ㅋ낮게주면',
 '영화입니다.조만간',
 '가득했으면',
 '쎄네!',
 '흔들리다가',
 '정신을',
 '후문이려나)',
 '몰입해',
 '소름돋네',
 '무슨소용인가...',
 '사전지식알고가면',
 '굿드~!',
 '지나치지',
 '길지않도록',
 '또만나보',
 '볼만하지',
 '아닐까?라는',
 '반응도',
 '좋고..',
 '아니었다..',
 '맞나싶을정도로',
 '얼마나뛰어난상상력을가지고있기에',
 '헐;;;집중안되고',
 '이런느낌은',
 '벙쪄있었다고나',
 '재밌내요',
 '아주좋아요',
 '전라도새끼들마냥',
 '엔딩.',
 '평가하리오...',
 '깨어보니',
 '뇌는정말',
 '됩니다',
 '우주적',
 '하품하고',
 '지루한거',
 '169분인줄',
 '그저그런영화인듯,',
 '우주다큐',
 '관통한다~!',
 '흥미있긴한데',
 '천문학도인데',
 '감성팔이에',
 '여자말들었으면',
 '들고나온듯하다.',
 '영화로긴장감이',
 '드릴',
 '스콧을',
 '프레스티지',
 'TV',
 '기억나질',
 '생각없는',
 '책읽으시고',
 '몰입감의',
 '영화..그리고',
 '(ㅇ..ㅇ);;;;',
 '패션왕봤으면',
 '세상에다시한번',
 '빠가라고',
 '감동받았네.',
 '한아버지로서',
 '또보고싶은

In [77]:
import numpy as np

layer_0 = np.zeros((1,vocab_size))
layer_0

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [78]:
word2index = {}

for i,word in enumerate(vocab):
    word2index[word] = i
word2index

{'': 0,
 '퀄리티로': 1,
 '영화임': 3,
 '아름다고': 59898,
 '중요하지만...': 4,
 '왜이리도긴지': 29127,
 '답답하기도': 5,
 '재미있었다.지구환경에': 2,
 '영화음악의': 30489,
 '<콘택트>보다': 39829,
 '든다는건': 6,
 '그걸전하는거같네요': 7,
 '내용면에서는': 9,
 '없었고,개인적으로는': 56576,
 '참신함만으로': 10,
 '훌륭해요.다크나이트의': 118663,
 'ㅋㅋㅋ3시간동안': 59901,
 '멍해졌다..너무': 19960,
 '판단할': 99754,
 '미래를.': 92725,
 '개소름...': 11,
 '어린왕자와': 12,
 '구원과': 13,
 '보지마세요;;;저도': 119499,
 '있습니다.OCN에서': 15,
 '잇엇던것같다기술,': 114961,
 '게임도': 16,
 '쩌렁': 9059,
 '이해할듯...': 17,
 '최고아닌게': 18,
 '그은': 19,
 '하거나': 21,
 '힘주는': 22,
 '특정장면': 93900,
 '나을것도': 23,
 '주인공.2.': 24,
 '욕심에': 25,
 '이해못하면': 27,
 '살았겠죠': 28,
 '보통': 99757,
 '안타깝네요.제가': 59906,
 '영화음악': 32,
 '통탄할': 99759,
 '알거같네요': 33,
 '감동적입니다.': 34,
 'ㅋ낮게주면': 35,
 '영화입니다.조만간': 36,
 '가득했으면': 37,
 '재미로보는': 79781,
 'Good!!!!': 39837,
 '쎄네!': 38,
 '흔들리다가': 39,
 '6개월이': 19964,
 '정신을': 40,
 '후문이려나)': 41,
 '몰입해': 42,
 '굿드~!': 46,
 '하겠다꿀잼': 110782,
 '지나치지': 47,
 '길지않도록': 48,
 '또만나보': 49,
 '알것같아요!!!': 108050,
 '아닐까?라는': 51,
 '정점더': 19967,
 '모욕감을': 99763,
 '좋고

In [87]:
def get_target_for_label(label):
    if(label == 'POSITIVE'):
        return 1
    else:
        return 0

In [88]:
labels[0]

'POSITIVE'

In [89]:
get_target_for_label(labels[0])

1

In [90]:
labels[1]

'POSITIVE'

In [91]:
get_target_for_label(labels[1])

1

In [92]:
def update_input_layer(review):
    
    global layer_0
    
    # clear out previous state, reset the layer to be all 0s
    layer_0 *= 0
    for word in review.split(" "):
        layer_0[0][word2index[word]] += 1

update_input_layer(reviews[0])

In [93]:
layer_0

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [94]:
review_counter = Counter()

In [95]:
for word in reviews[0].split(" "):
    review_counter[word] += 1

In [96]:
review_counter.most_common()

[('느껴진다.', 1),
 ('대단하다', 1),
 ('인셉션은', 1),
 ('경이롭다고', 1),
 ('느꼈는데,', 1),
 ('인터스텔라는', 1)]

In [97]:
layer_0 = np.zeros(10)

In [98]:
layer_0

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [99]:
layer_0[4] = 1
layer_0[9] = 1

In [100]:
layer_0

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.])

In [101]:
weights_0_1 = np.random.randn(10,5)

In [102]:
layer_0.dot(weights_0_1)

array([-1.68683952, -0.23045614,  1.85749624,  0.52929535, -0.87338041])

In [103]:
indices = [4,9]

In [104]:
layer_1 = np.zeros(5)

In [105]:
for index in indices:
    layer_1 += (weights_0_1[index])

In [106]:
layer_1

array([-1.68683952, -0.23045614,  1.85749624,  0.52929535, -0.87338041])

In [108]:
# words most frequently seen in a review with a "POSITIVE" label
pos_neg_ratios.most_common()

[('말로', 5.7838251823297373),
 ('내인생', 5.2781146592305168),
 ('필요없다', 4.8751973232011512),
 ('꼭보세요', 4.8202815656050371),
 ('필요없다.', 4.7706846244656651),
 ('인생영화', 4.7621739347977563),
 ('필요없는', 4.5108595065168497),
 ('눈물이', 4.4886363697321396),
 ('표현할', 4.4773368144782069),
 ('최고의', 4.3653708366271395),
 ('인생', 4.3400879454535515),
 ('꼭', 4.240903472141146),
 ('감히', 4.2121275978784842),
 ('평생', 4.1190371748124726),
 ('최고', 4.0990951649806986),
 ('여운이', 4.0661736852554045),
 ('죽기전에', 4.0517849478033048),
 ('3시간이', 4.048300623720694),
 ('말이', 4.0384237723025018),
 ('안보면', 3.9796816539019608),
 ('모르게', 3.970291913552122),
 ('소름이', 3.9269116179218968),
 ('필요', 3.9252682321781664),
 ('몰입해서', 3.9219733362813143),
 ('생에', 3.912023005428146),
 ('느낄', 3.9053340172773492),
 ('시간가는줄', 3.9019726695746448),
 ('살면서', 3.8836235309064482),
 ('영화!!', 3.8286413964890951),
 ('생애', 3.7689221617874726),
 ('경이롭다.', 3.755369195382769),
 ('보세요', 3.7226768336972271),
 ('보고싶은', 3.6971782569286313),
 ('경이로움', 3.

In [109]:
# words most frequently seen in a review with a "NEGATIVE" label
list(reversed(pos_neg_ratios.most_common()))[0:30]

[('지루하고', -1.0763800632689959),
 ('평점이', -0.56010151739366976),
 ('기대가', -0.32830279898303005),
 ('없고', -0.16403810943294475),
 ('다들', 0.039220713153281329),
 ('솔직히', 0.087011376989629685),
 ('훨씬', 0.22314355131420976),
 ('기대하고', 0.24116205681688804),
 ('생각보다', 0.30873548164961323),
 ('재미는', 0.33349160848307507),
 ('재미가', 0.34294475112683043),
 ('보다가', 0.40546510810816438),
 ('그렇게', 0.42433359241254714),
 ('뭐', 0.46798546508949834),
 ('딱', 0.47762755435639487),
 ('그런지', 0.53492317534505118),
 ('나름', 0.61090908232297314),
 ('기대를', 0.61455690596672374),
 ('스토리가', 0.63779708547678038),
 ('내용은', 0.65587578576271366),
 ('지루한', 0.66904962898088483),
 ('이게', 0.68072466056138814),
 ('저는', 0.70556970055850243),
 ('결국', 0.81377516834856001),
 ('내용도', 0.82098055206983034),
 ('너무', 0.82286614004981196),
 ('아니다', 0.8286926725561693),
 ('넘', 0.85938259960227559),
 ('사람들이', 0.86808863005627734),
 ('좀', 0.88465364693097248)]

In [111]:
from bokeh.models import ColumnDataSource, LabelSet
from bokeh.plotting import figure, show, output_file
from bokeh.io import output_notebook
output_notebook()

Loading BokehJS ...

In [112]:
hist, edges = np.histogram(list(map(lambda x:x[1],pos_neg_ratios.most_common())), density=True, bins=100, normed=True)

p = figure(tools="pan,wheel_zoom,reset,save",
           toolbar_location="above",
           title="Word Positive/Negative Affinity Distribution")
p.quad(top=hist, bottom=0, left=edges[:-1], right=edges[1:], line_color="#555555")
show(p)

In [113]:
frequency_frequency = Counter()

for word, cnt in total_counts.most_common():
    frequency_frequency[cnt] += 1

In [115]:
hist, edges = np.histogram(list(map(lambda x:x[1],frequency_frequency.most_common())), density=True, bins=100, normed=True)

p = figure(tools="pan,wheel_zoom,reset,save",
           toolbar_location="above",
           title="The frequency distribution of the words in our corpus")
p.quad(top=hist, bottom=0, left=edges[:-1], right=edges[1:], line_color="#555555")
show(p)

In [116]:
import time
import sys
import numpy as np

# Let's tweak our network from before to model these phenomena
class SentimentNetwork:
    def __init__(self, reviews,labels,min_count = 10,polarity_cutoff = 0.1,hidden_nodes = 10, learning_rate = 0.1):
       
        np.random.seed(1)
    
        self.pre_process_data(reviews, polarity_cutoff, min_count)
        
        self.init_network(len(self.review_vocab),hidden_nodes, 1, learning_rate)
        
        
    def pre_process_data(self,reviews, polarity_cutoff,min_count):
        
        positive_counts = Counter()
        negative_counts = Counter()
        total_counts = Counter()

        for i in range(len(reviews)):
            if(labels[i] == 'POSITIVE'):
                for word in reviews[i].split(" "):
                    positive_counts[word] += 1
                    total_counts[word] += 1
            else:
                for word in reviews[i].split(" "):
                    negative_counts[word] += 1
                    total_counts[word] += 1

        pos_neg_ratios = Counter()

        for term,cnt in list(total_counts.most_common()):
            if(cnt >= 50):
                pos_neg_ratio = positive_counts[term] / float(negative_counts[term]+1)
                pos_neg_ratios[term] = pos_neg_ratio

        for word,ratio in pos_neg_ratios.most_common():
            if(ratio > 1):
                pos_neg_ratios[word] = np.log(ratio)
            else:
                pos_neg_ratios[word] = -np.log((1 / (ratio + 0.01)))
        
        review_vocab = set()
        for review in reviews:
            for word in review.split(" "):
                if(total_counts[word] > min_count):
                    if(word in pos_neg_ratios.keys()):
                        if((pos_neg_ratios[word] >= polarity_cutoff) or (pos_neg_ratios[word] <= -polarity_cutoff)):
                            review_vocab.add(word)
                    else:
                        review_vocab.add(word)
        self.review_vocab = list(review_vocab)
        
        label_vocab = set()
        for label in labels:
            label_vocab.add(label)
        
        self.label_vocab = list(label_vocab)
        
        self.review_vocab_size = len(self.review_vocab)
        self.label_vocab_size = len(self.label_vocab)
        
        self.word2index = {}
        for i, word in enumerate(self.review_vocab):
            self.word2index[word] = i
        
        self.label2index = {}
        for i, label in enumerate(self.label_vocab):
            self.label2index[label] = i
         
        
    def init_network(self, input_nodes, hidden_nodes, output_nodes, learning_rate):
        # Set number of nodes in input, hidden and output layers.
        self.input_nodes = input_nodes
        self.hidden_nodes = hidden_nodes
        self.output_nodes = output_nodes

        # Initialize weights
        self.weights_0_1 = np.zeros((self.input_nodes,self.hidden_nodes))
    
        self.weights_1_2 = np.random.normal(0.0, self.output_nodes**-0.5, 
                                                (self.hidden_nodes, self.output_nodes))
        
        self.learning_rate = learning_rate
        
        self.layer_0 = np.zeros((1,input_nodes))
        self.layer_1 = np.zeros((1,hidden_nodes))
        
    def sigmoid(self,x):
        return 1 / (1 + np.exp(-x))
    
    
    def sigmoid_output_2_derivative(self,output):
        return output * (1 - output)
    
    def update_input_layer(self,review):

        # clear out previous state, reset the layer to be all 0s
        self.layer_0 *= 0
        for word in review.split(" "):
            self.layer_0[0][self.word2index[word]] = 1

    def get_target_for_label(self,label):
        if(label == 'POSITIVE'):
            return 1
        else:
            return 0
        
    def train(self, training_reviews_raw, training_labels):
        
        training_reviews = list()
        for review in training_reviews_raw:
            indices = set()
            for word in review.split(" "):
                if(word in self.word2index.keys()):
                    indices.add(self.word2index[word])
            training_reviews.append(list(indices))
        
        assert(len(training_reviews) == len(training_labels))
        
        correct_so_far = 0
        
        start = time.time()
        
        for i in range(len(training_reviews)):
            
            review = training_reviews[i]
            label = training_labels[i]
            
            #### Implement the forward pass here ####
            ### Forward pass ###

            # Input Layer

            # Hidden layer
#             layer_1 = self.layer_0.dot(self.weights_0_1)
            self.layer_1 *= 0
            for index in review:
                self.layer_1 += self.weights_0_1[index]
            
            # Output layer
            layer_2 = self.sigmoid(self.layer_1.dot(self.weights_1_2))

            #### Implement the backward pass here ####
            ### Backward pass ###

            # Output error
            layer_2_error = layer_2 - self.get_target_for_label(label) # Output layer error is the difference between desired target and actual output.
            layer_2_delta = layer_2_error * self.sigmoid_output_2_derivative(layer_2)

            # Backpropagated error
            layer_1_error = layer_2_delta.dot(self.weights_1_2.T) # errors propagated to the hidden layer
            layer_1_delta = layer_1_error # hidden layer gradients - no nonlinearity so it's the same as the error

            # Update the weights
            self.weights_1_2 -= self.layer_1.T.dot(layer_2_delta) * self.learning_rate # update hidden-to-output weights with gradient descent step
            
            for index in review:
                self.weights_0_1[index] -= layer_1_delta[0] * self.learning_rate # update input-to-hidden weights with gradient descent step

            if(layer_2 >= 0.5 and label == 'POSITIVE'):
                correct_so_far += 1
            if(layer_2 < 0.5 and label == 'NEGATIVE'):
                correct_so_far += 1
            
            reviews_per_second = i /( float(time.time() - start)+0.0000001)
            
            sys.stdout.write("\rProgress:" + str(100 * i/float(len(training_reviews)))[:4] + "% Speed(reviews/sec):" + str(reviews_per_second)[0:5] + " #Correct:" + str(correct_so_far) + " #Trained:" + str(i+1) + " Training Accuracy:" + str(correct_so_far * 100 / float(i+1))[:4] + "%")
        
    
    def test(self, testing_reviews, testing_labels):
        
        correct = 0
        
        start = time.time()
        
        for i in range(len(testing_reviews)):
            pred = self.run(testing_reviews[i])
            if(pred == testing_labels[i]):
                correct += 1
            
            reviews_per_second = i / (float(time.time() - start)+0.000001)
            
            sys.stdout.write("\rProgress:" + str(100 * i/float(len(testing_reviews)))[:4] \
                             + "% Speed(reviews/sec):" + str(reviews_per_second)[0:5] \
                            + "% #Correct:" + str(correct) + " #Tested:" + str(i+1) + " Testing Accuracy:" + str(correct * 100 / float(i+1))[:4] + "%")
    
    def run(self, review):
        
        # Input Layer


        # Hidden layer
        self.layer_1 *= 0
        unique_indices = set()
        for word in review.lower().split(" "):
            if word in self.word2index.keys():
                unique_indices.add(self.word2index[word])
        for index in unique_indices:
            self.layer_1 += self.weights_0_1[index]
        
        # Output layer
        layer_2 = self.sigmoid(self.layer_1.dot(self.weights_1_2))
        
        if(layer_2[0] >= 0.5):
            return "POSITIVE"
        else:
            return "NEGATIVE"
        

In [159]:
mlp = SentimentNetwork(reviews[:-10000],labels[:-10000],min_count=20,polarity_cutoff=0.05,learning_rate=0.001)

In [160]:
mlp.train(reviews[:-10000],labels[:-10000])

Progress:99.9% Speed(reviews/sec):6903. #Correct:35344 #Trained:37582 Training Accuracy:94.0%

In [161]:
mlp.test(reviews[-10000:],labels[-10000:])

Progress:99.9% Speed(reviews/sec):8074.% #Correct:7039 #Tested:10000 Testing Accuracy:70.3%

In [162]:
mlp = SentimentNetwork(reviews[:-10000],labels[:-10000],min_count=20,polarity_cutoff=0.8,learning_rate=0.001)

In [163]:
mlp.train(reviews[:-10000],labels[:-10000])

Progress:99.9% Speed(reviews/sec):6803. #Correct:35353 #Trained:37582 Training Accuracy:94.0%

In [164]:
mlp.test(reviews[-10000:],labels[-10000:])

Progress:99.9% Speed(reviews/sec):8275.% #Correct:7039 #Tested:10000 Testing Accuracy:70.3%

In [165]:
mlp_full = SentimentNetwork(reviews[:-10000],labels[:-10000],min_count=0,polarity_cutoff=0,learning_rate=0.0001)

In [166]:
mlp_full.train(reviews[:-10000],labels[:-10000])

Progress:99.9% Speed(reviews/sec):5825. #Correct:35345 #Trained:37582 Training Accuracy:94.0%

In [167]:
def get_most_similar_words(focus = "최악"):
    most_similar = Counter()

    for word in mlp_full.word2index.keys():
        most_similar[word] = np.dot(mlp_full.weights_0_1[mlp_full.word2index[word]],mlp_full.weights_0_1[mlp_full.word2index[focus]])
    
    return most_similar.most_common()

In [168]:
get_most_similar_words("최고")

[('영화', 0.001410663602586168),
 ('', 0.0012583978956673262),
 ('정말', 0.0012018782538938564),
 ('진짜', 0.00098309771452629669),
 ('최고의', 0.00087710513488768965),
 ('영화를', 0.00081329374877039105),
 ('이', 0.00074220391513715072),
 ('수', 0.00066792461027540147),
 ('그냥', 0.00051698113608251528),
 ('영화가', 0.00051112527320841018),
 ('꼭', 0.00049768134266096854),
 ('더', 0.00047324124451940684),
 ('말이', 0.00046764590154693605),
 ('영화는', 0.00044250362018974777),
 ('본', 0.00044064149904419065),
 ('너무', 0.00043544387668653303),
 ('보고', 0.0004258766361726495),
 ('내', 0.00042582449074437027),
 ('영화.', 0.00042538160915534223),
 ('이런', 0.00042093477906915151),
 ('그', 0.00039457102088114927),
 ('놀란', 0.00038401246887670605),
 ('내가', 0.00036157893742192322),
 ('또', 0.00033125560082396336),
 ('이건', 0.00031678933489312169),
 ('잘', 0.00031079186579227553),
 ('있는', 0.00029754653495464589),
 ('다시', 0.00029737909274242394),
 ('3시간이', 0.00026730132255582727),
 ('역시', 0.00024435550633410331),
 ('크리스토퍼', 0.000235

In [169]:
get_most_similar_words("최악")

[('지루하고', 1.7564230212498814e-07),
 ('최악의', 5.059740988418783e-08),
 ('재미없다.', 3.8509317283738226e-08),
 ('개연성도', 3.4453778643191968e-08),
 ('거품이', 3.4422000281898629e-08),
 ('잔치에', 3.2713892874529711e-08),
 ('알바들', 3.1168267178101721e-08),
 ('지루하다.', 2.9634025254838588e-08),
 ('과대평가', 2.8892609724551226e-08),
 ('기대가', 2.8866429694415106e-08),
 ('소문난', 2.8279631000104232e-08),
 ('그닥', 2.7923119917102847e-08),
 ('그닥..', 2.4976598402379428e-08),
 ('우리나라에서', 2.4739121721445417e-08),
 ('한국에서만', 2.4372780702004216e-08),
 ('낚여서', 2.4281034600340493e-08),
 ('아는척', 2.4031116956675531e-08),
 ('별로였음', 2.3908306953453624e-08),
 ('황당', 2.3739875231329144e-08),
 ('과대', 2.3518852945214256e-08),
 ('노잼', 2.3498418731886134e-08),
 ('지루했어요', 2.2876888451706102e-08),
 ('나쁘지', 2.2123286167749228e-08),
 ('지나치게', 2.1974787345781022e-08),
 ('소재는', 2.1653553030704742e-08),
 ('과대평가된', 1.9931525246640357e-08),
 ('한국인들', 1.972332537447066e-08),
 ('열광하는', 1.963575483431831e-08),
 ('억지스런', 1.9488378669880778e-08),

In [170]:
import matplotlib.colors as colors

words_to_visualize = list()
for word, ratio in pos_neg_ratios.most_common(500):
    if(word in mlp_full.word2index.keys()):
        words_to_visualize.append(word)
    
for word, ratio in list(reversed(pos_neg_ratios.most_common()))[0:500]:
    if(word in mlp_full.word2index.keys()):
        words_to_visualize.append(word)

In [171]:
pos = 0
neg = 0

colors_list = list()
vectors_list = list()
for word in words_to_visualize:
    if word in pos_neg_ratios.keys():
        vectors_list.append(mlp_full.weights_0_1[mlp_full.word2index[word]])
        if(pos_neg_ratios[word] > 0):
            pos+=1
            colors_list.append("#00ff00")
        else:
            neg+=1
            colors_list.append("#000000")
    

In [172]:
from sklearn.manifold import TSNE
tsne = TSNE(n_components=2, random_state=0)
words_top_ted_tsne = tsne.fit_transform(vectors_list)

In [173]:
p = figure(tools="pan,wheel_zoom,reset,save",
           toolbar_location="above",
           title="vector T-SNE for most polarized words")

source = ColumnDataSource(data=dict(x1=words_top_ted_tsne[:,0],
                                    x2=words_top_ted_tsne[:,1],
                                    names=words_to_visualize))

p.scatter(x="x1", y="x2", size=8, source=source,color=colors_list)

word_labels = LabelSet(x="x1", y="x2", text="names", y_offset=6,
                  text_font_size="8pt", text_color="#555555",
                  source=source, text_align='center')
p.add_layout(word_labels)

show(p)

# green indicates positive words, black indicates negative words

C:\Anaconda3\envs\tf3.5\lib\site-packages\bokeh\util\deprecation.py:34: BokehDeprecationWarning: 
Supplying a user-defined data source AND iterable values to glyph methods is deprecated.

See https://github.com/bokeh/bokeh/issues/2056 for more information.

  warn(message)
C:\Anaconda3\envs\tf3.5\lib\site-packages\bokeh\util\deprecation.py:34: BokehDeprecationWarning: 
Supplying a user-defined data source AND iterable values to glyph methods is deprecated.

See https://github.com/bokeh/bokeh/issues/2056 for more information.

  warn(message)
