



# learnKOREAN - Emotional Classification


- github : https://github.com/Maxpridy




# Interstella, 10점 이상


# http://movie.naver.com/movie/bi/mi/basic.nhn?code=45290
    
네이버 영화 인터스텔라 리뷰들을 이용해서 분석.

지도 학습으로 그냥 아무런 형태소 분석 없이 Binary Classification을 간단하게 해본다.

인터스텔라는 평점이 9가 넘어가서 불균형이 심하지만 데이터가 매우 많다.(그리고 내가 좋아한다.)


10점 이상은 긍정, 9점 이하는 부정으로 했다. 총 47582 긍정 : 32966, 부정 : 14161이다.

사실 재미있게 본 사람들은 거의 10점을 주기때문에 해봤다.





In [140]:
fr = open('reviews.txt','r')
reviews = list(map(lambda x:x[:-1], fr.readlines()))
fr.close()

fl = open('labels.txt','r')
labels = list(map(lambda x:x[:-1].upper(), fl.readlines()))
fl.close()

In [141]:
len(reviews)

47582

In [142]:
reviews[0]

'인셉션은 대단하다 느꼈는데, 인터스텔라는 경이롭다고 느껴진다.'

In [143]:
labels[0]

'POSITIVE'

In [144]:
def print_review_and_label(i):
    print(labels[i] + "\t:\t" + reviews[i][:-1] + "...")


In [145]:
print("labels.txt \t : \t reviews.txt\n")

count = 1
for i in range(len(reviews)):
    if(labels[i] == 'NEGATIVE'):
        count = count+1
        print(count)
        print_review_and_label(i)
        
# ... 음..........................

labels.txt 	 : 	 reviews.txt

2
NEGATIVE	:	블랙홀도 ''사랑''은 빨아들이지 못했...
3
NEGATIVE	:	극장안은 만석이지만 무척 조용했...
4
NEGATIVE	:	누군가는 인터스텔라같은걸만들동안 누군가는 패션왕을 만든다...
5
NEGATIVE	:	아주 좋엇어  정말 아주아...
6
NEGATIVE	:	기발한상상력에 박수...
7
NEGATIVE	:	길었던 러닝타임의 그 끝은 광대했다그래비티를 보고 느꼇던 그 가슴벅참과어느 영화에도 느껴보지 못한 새로운 감동은내 뒤에서 팝콘을 와그적 씹어먹던 아저씨의거슬리는 소리가 더이상 들리지 않게 만들었다시각적인 부분은 이루 말할수 없이 아름다웠...
8
NEGATIVE	:	이 평점은 1점이 아니라 11점 버튼이 없어서 누르지 못한 나의 안타까운 마음을 표현한 것이...
9
NEGATIVE	:	 영화를 보고나서 영화를 평가할 자신이 없어졌...
10
NEGATIVE	:	와 진짜 이걸 빠는구나... 재미없는건 재미없는건데....
11
NEGATIVE	:	거품이 너무 많이 낀듯;; 과학적으로 오류도 많고 앞뒤 안 맞는 내용도 있다. 재미없다고 하면 이해못해서 그렇다고 욕먹음ㅋㅋㅋ 솔직히7점 정도 작품인데 거품많이끼고 아는''체''때문에 평가가 높아지는 작품인...
12
NEGATIVE	:	너무 과대포장 되었다...
13
NEGATIVE	:	실제 미국 캐나다에서는 영화상영나가는사람들엄청많고평도엄청안좋고 말도안되는영화라고 말많은데  한국은ㅋㅋㅋ...
14
NEGATIVE	:	도대체 영화보고난후에 사람들 반응이싸늘했는데 평점진짜 혐오스럽네스토리는 영화진행될수록 산으로가는데 지구가 위험하다면서 여정을떠나더니 그 주제는 안중에도없다 딸과아버지의 사랑이 큰 주제였더냐왜 유독 우리나라에서만 찬양하는거냐 ......
15
NEGATIVE	:	이영화가왜 우리나라에서만 잘되고 다른나라에서만 망한건지 이해가된다 나만그런건가? 노잼이...
16
NEGATIVE	:	지성인인척 영화볼줄 아는척 안습이네요 솔직

In [146]:
import numpy as np
from collections import Counter

In [147]:
positive_counts = Counter()
negative_counts = Counter()
total_counts = Counter()

In [148]:
for i in range(len(reviews)):
    if(labels[i] == 'POSITIVE'):
        for word in reviews[i].split(" "):
            positive_counts[word] += 1
            total_counts[word] += 1
    else:
        for word in reviews[i].split(" "):
            negative_counts[word] += 1
            total_counts[word] += 1

In [149]:
positive_counts.most_common()

[('', 4444),
 ('영화', 3418),
 ('정말', 2944),
 ('진짜', 2448),
 ('최고의', 2107),
 ('영화를', 2020),
 ('이', 1948),
 ('수', 1586),
 ('그냥', 1258),
 ('영화가', 1172),
 ('꼭', 1077),
 ('영화는', 1040),
 ('내', 1039),
 ('말이', 1033),
 ('이런', 1029),
 ('더', 1018),
 ('보고', 1017),
 ('너무', 1010),
 ('본', 941),
 ('영화.', 866),
 ('그', 861),
 ('놀란', 843),
 ('내가', 841),
 ('또', 706),
 ('이건', 704),
 ('다시', 605),
 ('있는', 580),
 ('인생', 528),
 ('볼', 524),
 ('잘', 493),
 ('다', 492),
 ('크리스토퍼', 487),
 ('없는', 485),
 ('어떻게', 479),
 ('보는', 477),
 ('3시간이', 473),
 ('이렇게', 453),
 ('것', 451),
 ('영화관에서', 443),
 ('역시', 436),
 ('그리고', 436),
 ('한번', 420),
 ('한', 406),
 ('내내', 406),
 ('와', 398),
 ('가장', 397),
 ('할', 389),
 ('최고', 388),
 ('평점', 385),
 ('인터스텔라', 379),
 ('대한', 376),
 ('놀란의', 369),
 ('아이맥스로', 341),
 ('영화다.', 330),
 ('.', 323),
 ('놀란은', 322),
 ('말로', 316),
 ('영화다', 308),
 ('시간이', 308),
 ('하는', 306),
 ('대단한', 304),
 ('여운이', 304),
 ('보세요', 304),
 ('영화에', 299),
 ('우주에', 298),
 ('인간의', 294),
 ('난', 288),
 ('계속', 282),
 ('봤는데', 276),


In [150]:
pos_neg_ratios = Counter()

for term,cnt in list(total_counts.most_common()):
    if(cnt > 100):
        pos_neg_ratio = positive_counts[term] / float(negative_counts[term]+1)
        pos_neg_ratios[term] = pos_neg_ratio

for word,ratio in pos_neg_ratios.most_common():
    if(ratio > 1):
        pos_neg_ratios[word] = np.log(ratio)
    else:
        pos_neg_ratios[word] = -np.log((1 / (ratio+0.01)))

In [151]:
pos_neg_ratios.most_common()

[('내인생', 3.8763958277849948),
 ('인생영화', 3.6463198396951406),
 ('태어나서', 3.5481795720108011),
 ('인생', 3.4965075614664802),
 ('필요없다', 3.4657359027997265),
 ('말로', 3.4531571205928664),
 ('감히', 3.2733640101522705),
 ('생에', 3.1986731175506815),
 ('표현할', 3.1957534074473464),
 ('평생', 3.1780538303479458),
 ('필요없다.', 3.1267605359603952),
 ('죽기전에', 2.917770732084279),
 ('최고의', 2.8327388481991522),
 ('살면서', 2.8162637857424428),
 ('말이', 2.7813393857599666),
 ('최고다', 2.6936614636501104),
 ('꼭보세요', 2.6827323931179201),
 ('필요', 2.6741486494265287),
 ('필요없는', 2.6625878270254528),
 ('생애', 2.6230569882688175),
 ('역대', 2.5839975524322312),
 ('봐라', 2.5649493574615367),
 ('안보면', 2.4700915640028596),
 ('명작', 2.4223862928066664),
 ('이런영화를', 2.3353749158170367),
 ('눈물이', 2.3272777055844172),
 ('인터스텔라를', 2.3223877202902252),
 ('전율이', 2.2512917986064953),
 ('최고', 2.2474332729189657),
 ('보세요.', 2.2464956263430023),
 ('소름이', 2.2353763433005955),
 ('영화중에', 2.231357583705678),
 ('소름', 2.224623551524334),
 ('지금까지', 2

In [152]:
list(reversed(pos_neg_ratios.most_common()))[0:30]
# 음....................

[('재미는', -2.1561564592606977),
 ('지루하고', -2.0382753026210634),
 ('기대가', -2.0113379543777685),
 ('나름', -1.6255002904442297),
 ('지루한', -1.3214180591988343),
 ('생각보다', -1.2016499229097961),
 ('다소', -1.1274173604373068),
 ('다만', -1.0918907429077829),
 ('살짝', -1.0135145061389195),
 ('조금', -0.98800469347546716),
 ('그런지', -0.96660984206386213),
 ('좀', -0.94820118286924004),
 ('그러나', -0.93158567690979266),
 ('평점이', -0.91372991101248136),
 ('내용은', -0.90300725616163291),
 ('그래도', -0.88644944012778537),
 ('초반', -0.87369253795264423),
 ('약간', -0.84665234451911919),
 ('볼만한', -0.81343334643444731),
 ('다들', -0.71690544717879778),
 ('솔직히', -0.71518896885558259),
 ('기대를', -0.6673478934133279),
 ('스토리가', -0.66553201352697189),
 ('부분도', -0.63852209336588006),
 ('있었지만', -0.63585890502252185),
 ('부분이', -0.6277162006393544),
 ('내용이', -0.60696948431889286),
 ('하지만', -0.60145864936692761),
 ('없고', -0.59685468240550987),
 ('기대하고', -0.59201782587438712)]

In [153]:
vocab = set(total_counts.keys())
vocab_size = len(vocab)
print(vocab_size)

119893


In [154]:
list(vocab)

['',
 '5차원공간을',
 '여자친구랑보는데',
 '단조로운',
 '진짜미친영화다...',
 '나올려면적어도',
 '못한것을',
 '더늙은거다',
 '아느냐',
 '있겠죠',
 '다름이다.',
 '숨이차보긴처음이네',
 '짜여',
 '영화.인생에',
 '흥행과',
 '잤움',
 'ㅣ믿고',
 '굿최고최고굿굿굿굿임',
 '처음이다.크리스토퍼의',
 'ㄸ',
 '당장CGV든',
 '가족들과의',
 '판타지적',
 '봤는데여!',
 '만들어놓는거봐라',
 '자리내주신',
 '허니버터칩',
 '철학적이에요',
 '사랑으로부터',
 '보면됌..',
 '과거,',
 '방대해서',
 '기대이상....진짜',
 '교수가',
 '또볼수있을까.',
 '너무너무보고싶었음ㅋㅋㅋ',
 '최고..두번봤지만',
 '길엇음에도',
 '안봄.',
 '느낌도..전혀',
 '말려면말어라',
 '유치하지만',
 '놀라울따름큰파도,',
 '강조되어',
 '생각해봤다.',
 '장면의',
 '감사했다.혼자',
 '어지간하면',
 '후자인',
 '충실해야할',
 '좁디좁은',
 '힘든부분도',
 '접해본',
 '퇴장시켜주지',
 '밀렸느지',
 '비난하는',
 '완전똑똑하신듯!!!',
 '사랑해!',
 '감흥도',
 '적는다',
 '영화...인.터.스.텔.라.~',
 '대박..소름끼친다',
 '10자이상으로',
 '들였습니다',
 '사랑사이의',
 '반사회인격장애',
 '자다가',
 '선물받았네요.ㅋㅋㅋ',
 '어디까지인가...그리고',
 '찾아볼수없었던',
 '요글래',
 '해리포터가',
 '환호',
 '난생처음이였다...과학을떠나서',
 '그간의',
 '심적으로',
 '평점...처음으로',
 '자식사랑에',
 '음료먹지말고',
 '종착역',
 '재밌더군요',
 '봤을듯.',
 '반항하는',
 '오랫도록',
 '만날때는',
 '재미있는지는',
 '후회하지말고',
 '무궁무지하단걸',
 '이거재밋다구',
 '만든영화..그래서',
 '허니버터칩먹르면서',
 '표현하다니3시간가까이',
 '모든직업군의'

In [155]:
import numpy as np

layer_0 = np.zeros((1,vocab_size))
layer_0

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [156]:
word2index = {}

for i,word in enumerate(vocab):
    word2index[word] = i
word2index

{'': 0,
 '5차원공간을': 1,
 '여자친구랑보는데': 2,
 '진짜미친영화다...': 4,
 '나올려면적어도': 5,
 '더늙은거다': 7,
 '아느냐': 8,
 '있겠죠': 9,
 '전해준': 110407,
 '짜여': 12,
 '못한것을': 6,
 '잤움': 15,
 '흥행과': 14,
 'ㅋㅋ대단히재밌는영화': 99837,
 'ㅣ믿고': 16,
 '가족들과의': 21,
 '당장CGV든': 20,
 '영화순위를': 39879,
 '판타지적': 22,
 '봤는데여!': 23,
 '철학적이에요': 27,
 '자리내주신': 25,
 '사랑으로부터': 28,
 '과거,': 30,
 '그냥그랫음..그치만': 9609,
 '방대해서': 31,
 '교수가': 33,
 '너무너무보고싶었음ㅋㅋㅋ': 35,
 '최고..두번봤지만': 36,
 '길엇음에도': 37,
 '4차원5차원,': 93179,
 '안봄.': 38,
 '느낌도..전혀': 39,
 '말려면말어라': 40,
 '유치하지만': 41,
 '놀라울따름큰파도,': 42,
 '장면의': 45,
 '후자인': 48,
 '어지간하면': 47,
 '충실해야할': 49,
 '힘든부분도': 51,
 '접해본': 52,
 '사랑해!': 57,
 '비난하는': 55,
 '완전똑똑하신듯!!!': 56,
 '감흥도': 58,
 '적는다': 59,
 '영화...인.터.스.텔.라.~': 60,
 '대박..소름끼친다': 61,
 '10자이상으로': 62,
 '들였습니다': 63,
 '구ㅡㅅ': 79682,
 '사랑사이의': 64,
 '반사회인격장애': 65,
 '자다가': 66,
 '선물받았네요.ㅋㅋㅋ': 67,
 '어디까지인가...그리고': 68,
 '찾아볼수없었던': 69,
 '요글래': 70,
 '해리포터가': 71,
 '환호': 72,
 '무슨단어로': 19971,
 '난생처음이였다...과학을떠나서': 73,
 '전달한거?ㅡㅡ': 99845,
 '평점...처음으로': 76,
 '심적으로': 75,
 '중요성을...이과': 

In [157]:
def get_target_for_label(label):
    if(label == 'POSITIVE'):
        return 1
    else:
        return 0

In [158]:
labels[0]

'POSITIVE'

In [159]:
get_target_for_label(labels[0])

1

In [160]:
labels[1]

'POSITIVE'

In [161]:
get_target_for_label(labels[1])

1

In [162]:
def update_input_layer(review):
    
    global layer_0
    
    # clear out previous state, reset the layer to be all 0s
    layer_0 *= 0
    for word in review.split(" "):
        layer_0[0][word2index[word]] += 1

update_input_layer(reviews[0])

In [163]:
layer_0

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [164]:
review_counter = Counter()

In [165]:
for word in reviews[0].split(" "):
    review_counter[word] += 1

In [166]:
review_counter.most_common()

[('인터스텔라는', 1),
 ('경이롭다고', 1),
 ('느껴진다.', 1),
 ('느꼈는데,', 1),
 ('인셉션은', 1),
 ('대단하다', 1)]

In [167]:
layer_0 = np.zeros(10)

In [168]:
layer_0

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [169]:
layer_0[4] = 1
layer_0[9] = 1

In [170]:
layer_0

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.])

In [171]:
weights_0_1 = np.random.randn(10,5)

In [172]:
layer_0.dot(weights_0_1)

array([-0.10503756,  0.44222989,  0.24392938, -0.55961832,  0.21389503])

In [173]:
indices = [4,9]

In [174]:
layer_1 = np.zeros(5)

In [175]:
for index in indices:
    layer_1 += (weights_0_1[index])

In [176]:
layer_1

array([-0.10503756,  0.44222989,  0.24392938, -0.55961832,  0.21389503])

In [177]:
pos_neg_ratios.most_common()

[('내인생', 3.8763958277849948),
 ('인생영화', 3.6463198396951406),
 ('태어나서', 3.5481795720108011),
 ('인생', 3.4965075614664802),
 ('필요없다', 3.4657359027997265),
 ('말로', 3.4531571205928664),
 ('감히', 3.2733640101522705),
 ('생에', 3.1986731175506815),
 ('표현할', 3.1957534074473464),
 ('평생', 3.1780538303479458),
 ('필요없다.', 3.1267605359603952),
 ('죽기전에', 2.917770732084279),
 ('최고의', 2.8327388481991522),
 ('살면서', 2.8162637857424428),
 ('말이', 2.7813393857599666),
 ('최고다', 2.6936614636501104),
 ('꼭보세요', 2.6827323931179201),
 ('필요', 2.6741486494265287),
 ('필요없는', 2.6625878270254528),
 ('생애', 2.6230569882688175),
 ('역대', 2.5839975524322312),
 ('봐라', 2.5649493574615367),
 ('안보면', 2.4700915640028596),
 ('명작', 2.4223862928066664),
 ('이런영화를', 2.3353749158170367),
 ('눈물이', 2.3272777055844172),
 ('인터스텔라를', 2.3223877202902252),
 ('전율이', 2.2512917986064953),
 ('최고', 2.2474332729189657),
 ('보세요.', 2.2464956263430023),
 ('소름이', 2.2353763433005955),
 ('영화중에', 2.231357583705678),
 ('소름', 2.224623551524334),
 ('지금까지', 2

In [178]:
list(reversed(pos_neg_ratios.most_common()))[0:30]

[('재미는', -2.1561564592606977),
 ('지루하고', -2.0382753026210634),
 ('기대가', -2.0113379543777685),
 ('나름', -1.6255002904442297),
 ('지루한', -1.3214180591988343),
 ('생각보다', -1.2016499229097961),
 ('다소', -1.1274173604373068),
 ('다만', -1.0918907429077829),
 ('살짝', -1.0135145061389195),
 ('조금', -0.98800469347546716),
 ('그런지', -0.96660984206386213),
 ('좀', -0.94820118286924004),
 ('그러나', -0.93158567690979266),
 ('평점이', -0.91372991101248136),
 ('내용은', -0.90300725616163291),
 ('그래도', -0.88644944012778537),
 ('초반', -0.87369253795264423),
 ('약간', -0.84665234451911919),
 ('볼만한', -0.81343334643444731),
 ('다들', -0.71690544717879778),
 ('솔직히', -0.71518896885558259),
 ('기대를', -0.6673478934133279),
 ('스토리가', -0.66553201352697189),
 ('부분도', -0.63852209336588006),
 ('있었지만', -0.63585890502252185),
 ('부분이', -0.6277162006393544),
 ('내용이', -0.60696948431889286),
 ('하지만', -0.60145864936692761),
 ('없고', -0.59685468240550987),
 ('기대하고', -0.59201782587438712)]

In [179]:
from bokeh.models import ColumnDataSource, LabelSet
from bokeh.plotting import figure, show, output_file
from bokeh.io import output_notebook
output_notebook()

Loading BokehJS ...

In [180]:
hist, edges = np.histogram(list(map(lambda x:x[1],pos_neg_ratios.most_common())), density=True, bins=100, normed=True)

p = figure(tools="pan,wheel_zoom,reset,save",
           toolbar_location="above",
           title="Word Positive/Negative Affinity Distribution")
p.quad(top=hist, bottom=0, left=edges[:-1], right=edges[1:], line_color="#555555")
show(p)

In [181]:
frequency_frequency = Counter()

for word, cnt in total_counts.most_common():
    frequency_frequency[cnt] += 1

In [182]:
hist, edges = np.histogram(list(map(lambda x:x[1],frequency_frequency.most_common())), density=True, bins=100, normed=True)

p = figure(tools="pan,wheel_zoom,reset,save",
           toolbar_location="above",
           title="The frequency distribution of the words in our corpus")
p.quad(top=hist, bottom=0, left=edges[:-1], right=edges[1:], line_color="#555555")
show(p)

In [183]:
import time
import sys
import numpy as np

# Let's tweak our network from before to model these phenomena
class SentimentNetwork:
    def __init__(self, reviews,labels,min_count = 10,polarity_cutoff = 0.1,hidden_nodes = 10, learning_rate = 0.1):
       
        np.random.seed(1)
    
        self.pre_process_data(reviews, polarity_cutoff, min_count)
        
        self.init_network(len(self.review_vocab),hidden_nodes, 1, learning_rate)
        
        
    def pre_process_data(self,reviews, polarity_cutoff,min_count):
        
        positive_counts = Counter()
        negative_counts = Counter()
        total_counts = Counter()

        for i in range(len(reviews)):
            if(labels[i] == 'POSITIVE'):
                for word in reviews[i].split(" "):
                    positive_counts[word] += 1
                    total_counts[word] += 1
            else:
                for word in reviews[i].split(" "):
                    negative_counts[word] += 1
                    total_counts[word] += 1

        pos_neg_ratios = Counter()

        for term,cnt in list(total_counts.most_common()):
            if(cnt >= 50):
                pos_neg_ratio = positive_counts[term] / float(negative_counts[term]+1)
                pos_neg_ratios[term] = pos_neg_ratio

        for word,ratio in pos_neg_ratios.most_common():
            if(ratio > 1):
                pos_neg_ratios[word] = np.log(ratio)
            else:
                pos_neg_ratios[word] = -np.log((1 / (ratio + 0.01)))
        
        review_vocab = set()
        for review in reviews:
            for word in review.split(" "):
                if(total_counts[word] > min_count):
                    if(word in pos_neg_ratios.keys()):
                        if((pos_neg_ratios[word] >= polarity_cutoff) or (pos_neg_ratios[word] <= -polarity_cutoff)):
                            review_vocab.add(word)
                    else:
                        review_vocab.add(word)
        self.review_vocab = list(review_vocab)
        
        label_vocab = set()
        for label in labels:
            label_vocab.add(label)
        
        self.label_vocab = list(label_vocab)
        
        self.review_vocab_size = len(self.review_vocab)
        self.label_vocab_size = len(self.label_vocab)
        
        self.word2index = {}
        for i, word in enumerate(self.review_vocab):
            self.word2index[word] = i
        
        self.label2index = {}
        for i, label in enumerate(self.label_vocab):
            self.label2index[label] = i
         
        
    def init_network(self, input_nodes, hidden_nodes, output_nodes, learning_rate):
        # Set number of nodes in input, hidden and output layers.
        self.input_nodes = input_nodes
        self.hidden_nodes = hidden_nodes
        self.output_nodes = output_nodes

        # Initialize weights
        self.weights_0_1 = np.zeros((self.input_nodes,self.hidden_nodes))
    
        self.weights_1_2 = np.random.normal(0.0, self.output_nodes**-0.5, 
                                                (self.hidden_nodes, self.output_nodes))
        
        self.learning_rate = learning_rate
        
        self.layer_0 = np.zeros((1,input_nodes))
        self.layer_1 = np.zeros((1,hidden_nodes))
        
    def sigmoid(self,x):
        return 1 / (1 + np.exp(-x))
    
    
    def sigmoid_output_2_derivative(self,output):
        return output * (1 - output)
    
    def update_input_layer(self,review):

        # clear out previous state, reset the layer to be all 0s
        self.layer_0 *= 0
        for word in review.split(" "):
            self.layer_0[0][self.word2index[word]] = 1

    def get_target_for_label(self,label):
        if(label == 'POSITIVE'):
            return 1
        else:
            return 0
        
    def train(self, training_reviews_raw, training_labels):
        
        training_reviews = list()
        for review in training_reviews_raw:
            indices = set()
            for word in review.split(" "):
                if(word in self.word2index.keys()):
                    indices.add(self.word2index[word])
            training_reviews.append(list(indices))
        
        assert(len(training_reviews) == len(training_labels))
        
        correct_so_far = 0
        
        start = time.time()
        
        for i in range(len(training_reviews)):
            
            review = training_reviews[i]
            label = training_labels[i]
            
            #### Implement the forward pass here ####
            ### Forward pass ###

            # Input Layer

            # Hidden layer
#             layer_1 = self.layer_0.dot(self.weights_0_1)
            self.layer_1 *= 0
            for index in review:
                self.layer_1 += self.weights_0_1[index]
            
            # Output layer
            layer_2 = self.sigmoid(self.layer_1.dot(self.weights_1_2))

            #### Implement the backward pass here ####
            ### Backward pass ###

            # Output error
            layer_2_error = layer_2 - self.get_target_for_label(label) # Output layer error is the difference between desired target and actual output.
            layer_2_delta = layer_2_error * self.sigmoid_output_2_derivative(layer_2)

            # Backpropagated error
            layer_1_error = layer_2_delta.dot(self.weights_1_2.T) # errors propagated to the hidden layer
            layer_1_delta = layer_1_error # hidden layer gradients - no nonlinearity so it's the same as the error

            # Update the weights
            self.weights_1_2 -= self.layer_1.T.dot(layer_2_delta) * self.learning_rate # update hidden-to-output weights with gradient descent step
            
            for index in review:
                self.weights_0_1[index] -= layer_1_delta[0] * self.learning_rate # update input-to-hidden weights with gradient descent step

            if(layer_2 >= 0.5 and label == 'POSITIVE'):
                correct_so_far += 1
            if(layer_2 < 0.5 and label == 'NEGATIVE'):
                correct_so_far += 1
            
            reviews_per_second = i /( float(time.time() - start)+0.0000001)
            
            sys.stdout.write("\rProgress:" + str(100 * i/float(len(training_reviews)))[:4] + "% Speed(reviews/sec):" + str(reviews_per_second)[0:5] + " #Correct:" + str(correct_so_far) + " #Trained:" + str(i+1) + " Training Accuracy:" + str(correct_so_far * 100 / float(i+1))[:4] + "%")
        
    
    def test(self, testing_reviews, testing_labels):
        
        correct = 0
        
        start = time.time()
        
        for i in range(len(testing_reviews)):
            pred = self.run(testing_reviews[i])
            if(pred == testing_labels[i]):
                correct += 1
            
            reviews_per_second = i / (float(time.time() - start)+0.000001)
            
            sys.stdout.write("\rProgress:" + str(100 * i/float(len(testing_reviews)))[:4] \
                             + "% Speed(reviews/sec):" + str(reviews_per_second)[0:5] \
                            + "% #Correct:" + str(correct) + " #Tested:" + str(i+1) + " Testing Accuracy:" + str(correct * 100 / float(i+1))[:4] + "%")
    
    def run(self, review):
        
        # Input Layer


        # Hidden layer
        self.layer_1 *= 0
        unique_indices = set()
        for word in review.lower().split(" "):
            if word in self.word2index.keys():
                unique_indices.add(self.word2index[word])
        for index in unique_indices:
            self.layer_1 += self.weights_0_1[index]
        
        # Output layer
        layer_2 = self.sigmoid(self.layer_1.dot(self.weights_1_2))
        
        if(layer_2[0] >= 0.5):
            return "POSITIVE"
        else:
            return "NEGATIVE"
        

In [184]:
mlp = SentimentNetwork(reviews[:-10000],labels[:-10000],min_count=20,polarity_cutoff=0.05,learning_rate=0.001)

In [185]:
mlp.train(reviews[:-10000],labels[:-10000])

Progress:99.9% Speed(reviews/sec):6936. #Correct:29036 #Trained:37582 Training Accuracy:77.2%

In [186]:
mlp.test(reviews[-10000:],labels[-10000:])

Progress:99.9% Speed(reviews/sec):8788.% #Correct:5984 #Tested:10000 Testing Accuracy:59.8%

In [187]:
mlp = SentimentNetwork(reviews[:-10000],labels[:-10000],min_count=20,polarity_cutoff=0.8,learning_rate=0.001)

In [188]:
mlp.train(reviews[:-10000],labels[:-10000])

Progress:99.9% Speed(reviews/sec):7155. #Correct:28787 #Trained:37582 Training Accuracy:76.5%

In [189]:
mlp.test(reviews[-10000:],labels[-10000:])

Progress:99.9% Speed(reviews/sec):8745.% #Correct:5553 #Tested:10000 Testing Accuracy:55.5%

In [190]:
mlp_full = SentimentNetwork(reviews[:-10000],labels[:-10000],min_count=0,polarity_cutoff=0,learning_rate=0.0001)

In [191]:
mlp_full.train(reviews[:-10000],labels[:-10000])

Progress:99.9% Speed(reviews/sec):5751. #Correct:28863 #Trained:37582 Training Accuracy:76.8%

In [192]:
def get_most_similar_words(focus = "최악"):
    most_similar = Counter()

    for word in mlp_full.word2index.keys():
        most_similar[word] = np.dot(mlp_full.weights_0_1[mlp_full.word2index[word]],mlp_full.weights_0_1[mlp_full.word2index[focus]])
    
    return most_similar.most_common()

In [193]:
get_most_similar_words("최고")

[('정말', 0.00079257766685525302),
 ('진짜', 0.00077921767026834638),
 ('영화', 0.00076536921122329472),
 ('최고의', 0.00072122282600527339),
 ('영화를', 0.00056100415731705135),
 ('이', 0.0005436969563709967),
 ('', 0.00046973466794222917),
 ('수', 0.0003885847971368545),
 ('말이', 0.00037687168062032548),
 ('그냥', 0.00037539011733733231),
 ('꼭', 0.00037408324549497482),
 ('내', 0.00034273794217232586),
 ('영화가', 0.00033824129488159091),
 ('이런', 0.00030958701346077677),
 ('본', 0.00027993031672526593),
 ('보고', 0.0002788871434713835),
 ('내가', 0.00025884633163531298),
 ('영화는', 0.00025636260468782569),
 ('이건', 0.00025350586937520817),
 ('또', 0.00022973479613404432),
 ('놀란', 0.00022503178139956603),
 ('더', 0.00020674309530221256),
 ('그', 0.00020133710114175315),
 ('영화.', 0.00019780209701869135),
 ('인생', 0.00018176186188559632),
 ('다시', 0.0001595079027840086),
 ('크리스토퍼', 0.00015713359120490337),
 ('3시간이', 0.00014930132407327187),
 ('영화관에서', 0.0001443857471657214),
 ('이렇게', 0.00014383527844759523),
 ('볼', 0.00

In [194]:
get_most_similar_words("최악")

[('좀', 9.8572410596594624e-07),
 ('조금', 6.4343619290234256e-07),
 ('하지만', 4.2196122642242756e-07),
 ('다소', 3.2659955390662181e-07),
 ('그래도', 2.9858576123888458e-07),
 ('지루한', 2.9333720579667607e-07),
 ('약간', 2.893386525972748e-07),
 ('지루하고', 2.8176343325762937e-07),
 ('내용이', 2.4372397464374009e-07),
 ('기대를', 2.3116305557053233e-07),
 ('살짝', 2.1985680746574548e-07),
 ('나름', 2.153683465072111e-07),
 ('기대가', 2.1532830378721333e-07),
 ('솔직히', 2.1162194884123531e-07),
 ('재미는', 2.0339733563195223e-07),
 ('다만', 1.8294869836520804e-07),
 ('스토리가', 1.7128893289867155e-07),
 ('있었지만', 1.6405169750515701e-07),
 ('그러나', 1.4991204021566426e-07),
 ('부분이', 1.4963132953150248e-07),
 ('괜찮은', 1.4645178839882453e-07),
 ('9점', 1.414035053521167e-07),
 ('어려운', 1.3541227639387047e-07),
 ('재미도', 1.3333973055237165e-07),
 ('생각보다', 1.3169242038458655e-07),
 ('부분도', 1.311995454111458e-07),
 ('내용은', 1.310733184547809e-07),
 ('했지만', 1.2828499748740568e-07),
 ('조금은', 1.2613084946938576e-07),
 ('비해', 1.24636961398291

In [195]:
import matplotlib.colors as colors

words_to_visualize = list()
for word, ratio in pos_neg_ratios.most_common(500):
    if(word in mlp_full.word2index.keys()):
        words_to_visualize.append(word)
    
for word, ratio in list(reversed(pos_neg_ratios.most_common()))[0:500]:
    if(word in mlp_full.word2index.keys()):
        words_to_visualize.append(word)

In [196]:
pos = 0
neg = 0

colors_list = list()
vectors_list = list()
for word in words_to_visualize:
    if word in pos_neg_ratios.keys():
        vectors_list.append(mlp_full.weights_0_1[mlp_full.word2index[word]])
        if(pos_neg_ratios[word] > 0):
            pos+=1
            colors_list.append("#00ff00")
        else:
            neg+=1
            colors_list.append("#000000")
    

In [197]:
from sklearn.manifold import TSNE
tsne = TSNE(n_components=2, random_state=0)
words_top_ted_tsne = tsne.fit_transform(vectors_list)

In [198]:
p = figure(tools="pan,wheel_zoom,reset,save",
           toolbar_location="above",
           title="vector T-SNE for most polarized words")

source = ColumnDataSource(data=dict(x1=words_top_ted_tsne[:,0],
                                    x2=words_top_ted_tsne[:,1],
                                    names=words_to_visualize))

p.scatter(x="x1", y="x2", size=8, source=source,color=colors_list)

word_labels = LabelSet(x="x1", y="x2", text="names", y_offset=6,
                  text_font_size="8pt", text_color="#555555",
                  source=source, text_align='center')
p.add_layout(word_labels)

show(p)

# green indicates positive words, black indicates negative words

C:\Anaconda3\envs\tf3.5\lib\site-packages\bokeh\util\deprecation.py:34: BokehDeprecationWarning: 
Supplying a user-defined data source AND iterable values to glyph methods is deprecated.

See https://github.com/bokeh/bokeh/issues/2056 for more information.

  warn(message)
C:\Anaconda3\envs\tf3.5\lib\site-packages\bokeh\util\deprecation.py:34: BokehDeprecationWarning: 
Supplying a user-defined data source AND iterable values to glyph methods is deprecated.

See https://github.com/bokeh/bokeh/issues/2056 for more information.

  warn(message)


# Clustering 결과

드디어 부정이 보인다.